---
title: Mango CODE
timezone: UTC
email: hello@mangoco.de
description: Web development tips, techniques and tweaks.
baseurl: ''
url: https://mangoco.de
twitter_username: mangocode
github_username: mangocode
markdown: kramdown
permalink: "/:title"
paginate: 5
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-seo-tag
