---
title: Mango CODE
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@mangoco.de
description: Web development tips, techniques and tweaks.
baseurl: ''
url: https://mangoco.de
twitter_username: mangocode
github_username: mangocode
markdown: kramdown
theme: tale
remote_theme: chesterhow/tale
permalink: "/:year-:month-:day/:title"
paginate: 5
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-remote-theme
- jekyll-seo-tag
